# Generated by Django 5.0.4 on 2026-02-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="rating",
            field=models.IntegerField(default=5),
        ),
    ]
