# Generated by Django 5.0.4 on 2026-03-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0002_testimonial_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("rn", "Kirundi"),
                    ("en", "English"),
                    ("sw", "Kiswahili"),
                ],
                default="fr",
                max_length=2,
            ),
        ),
    ]
