# Generated by Django 5.0.4 on 2026-03-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0003_testimonial_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="author",
        ),
        migrations.AddField(
            model_name="testimonial",
            name="author_name",
            field=models.CharField(
                default="Anonyme", max_length=255, verbose_name="Auteur"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testimonial",
            name="author_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre/Rôle"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="content",
            field=models.TextField(verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publié"),
                    ("pending", "En attente"),
                    ("archived", "Archivé"),
                ],
                default="published",
                max_length=20,
            ),
        ),
    ]
