# Generated by Django 5.0.4 on 2026-02-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom de la paroisse"),
                ),
                (
                    "zone",
                    models.CharField(max_length=100, verbose_name="Zone / Commune"),
                ),
                (
                    "faithful",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nombre de fidèles"
                    ),
                ),
                (
                    "pastor",
                    models.CharField(max_length=255, verbose_name="Nom du Pasteur"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de téléphone"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paroisse",
                "verbose_name_plural": "Paroisses",
                "ordering": ["name"],
            },
        ),
    ]
