# Generated by Django 5.0.4 on 2026-02-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parishes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parish",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="parishes/",
                verbose_name="Photo de la paroisse",
            ),
        ),
    ]
