# Generated by Django 5.0.4 on 2026-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_create_default_settings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettings",
            old_name="about_content",
            new_name="about_content_fr",
        ),
        migrations.RenameField(
            model_name="sitesettings",
            old_name="contact_content",
            new_name="contact_content_fr",
        ),
        migrations.RenameField(
            model_name="sitesettings",
            old_name="hero_subtitle",
            new_name="hero_subtitle_fr",
        ),
        migrations.RenameField(
            model_name="sitesettings",
            old_name="hero_title",
            new_name="hero_title_fr",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_content_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_content_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_content_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_content_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_content_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_content_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subtitle_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subtitle_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subtitle_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_title_en",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_title_rn",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_title_sw",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
