# Generated by Django 5.0.4 on 2026-01-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_add_multilingual_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="bible_verse_en",
            field=models.TextField(
                blank=True,
                default="May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit!",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bible_verse_fr",
            field=models.TextField(
                blank=True,
                default="Que le Dieu de l'espérance vous remplisse de toute joie et de toute paix dans la foi, pour que vous abondiez en espérance par la puissance du Saint-Esprit !",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bible_verse_ref_en",
            field=models.CharField(blank=True, default="Romans 15:13", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bible_verse_ref_fr",
            field=models.CharField(blank=True, default="Romains 15:13", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bible_verse_ref_rn",
            field=models.CharField(blank=True, default="Abaroma 15:13", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bible_verse_ref_sw",
            field=models.CharField(blank=True, default="Warumi 15:13", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bible_verse_rn",
            field=models.TextField(
                blank=True,
                default="Imana y'ihuze ikuzuze amarara yose n'amahoro mu kwizera, kugira ngo muhenuke mw'ihuze ku mbaraga z'Umupfumu Mutagatifu!",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bible_verse_sw",
            field=models.TextField(
                blank=True,
                default="Mungu wa matumaini na akujaze furaha yote na amani katika kuamini, ili upate wingi wa matumaini kwa nguvu ya Roho Mtakatifu!",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_emissions_en",
            field=models.CharField(blank=True, default="Broadcasts", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_emissions_fr",
            field=models.CharField(blank=True, default="Émissions", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_emissions_rn",
            field=models.CharField(blank=True, default="Imitangire", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_emissions_sw",
            field=models.CharField(blank=True, default="Matangazo", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_meditation_en",
            field=models.CharField(
                blank=True, default="Words of Meditation", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_meditation_fr",
            field=models.CharField(
                blank=True, default="Paroles de méditation", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_meditation_rn",
            field=models.CharField(
                blank=True, default="Amagambo yo gutekereza", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_meditation_sw",
            field=models.CharField(
                blank=True, default="Maneno ya Kutafakari", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_teachings_en",
            field=models.CharField(blank=True, default="Teachings", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_teachings_fr",
            field=models.CharField(blank=True, default="Enseignements", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_teachings_rn",
            field=models.CharField(blank=True, default="Inyigisho", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_teachings_sw",
            field=models.CharField(blank=True, default="Mafundisho", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_categories_desc_en",
            field=models.TextField(
                blank=True,
                default="Explore our different broadcast categories to enrich your spiritual life",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_categories_desc_fr",
            field=models.TextField(
                blank=True,
                default="Explorez nos différentes catégories d'émissions pour enrichir votre vie spirituelle",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_categories_desc_rn",
            field=models.TextField(
                blank=True,
                default="Menya amoko yose yo kugira ngo urushirize ubuzima bwawe bw'umwuka",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_categories_desc_sw",
            field=models.TextField(
                blank=True,
                default="Chunguza jamii zetu tofauti za matangazo ili kuimarisha maisha yako ya kiroho",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_categories_en",
            field=models.CharField(blank=True, default="Categories", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_categories_fr",
            field=models.CharField(blank=True, default="Catégories", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_categories_rn",
            field=models.CharField(blank=True, default="Jamii", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_categories_sw",
            field=models.CharField(blank=True, default="Jamii", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_en",
            field=models.CharField(
                blank=True, default="Featured Broadcasts", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_fr",
            field=models.CharField(
                blank=True, default="Émissions en vedette", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_rn",
            field=models.CharField(
                blank=True, default="Imitangire ikomeye", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_sw",
            field=models.CharField(
                blank=True, default="Matangazo Maalum", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_audience_en",
            field=models.CharField(blank=True, default="Listeners", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_audience_fr",
            field=models.CharField(blank=True, default="Auditeurs", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_audience_rn",
            field=models.CharField(blank=True, default="Abatega", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_audience_sw",
            field=models.CharField(blank=True, default="Wasikilizaji", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_emissions_en",
            field=models.CharField(blank=True, default="Broadcasts", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_emissions_fr",
            field=models.CharField(blank=True, default="Émissions", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_emissions_rn",
            field=models.CharField(blank=True, default="Imitangire", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_emissions_sw",
            field=models.CharField(blank=True, default="Matangazo", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_languages_en",
            field=models.CharField(blank=True, default="Languages", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_languages_fr",
            field=models.CharField(blank=True, default="Langues", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_languages_rn",
            field=models.CharField(blank=True, default="Indimi", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_languages_sw",
            field=models.CharField(blank=True, default="Lugha", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_en",
            field=models.CharField(blank=True, default="Grow in Faith", max_length=200),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_rn",
            field=models.CharField(
                blank=True, default="Kura mu Kwizera", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_sw",
            field=models.CharField(
                blank=True, default="Kua katika Imani", max_length=200
            ),
        ),
    ]
