# Generated by Django 5.0.4 on 2026-01-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_add_ui_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="accent_color",
            field=models.CharField(
                blank=True,
                default="#8B5CF6",
                help_text="Couleur d'accentuation",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="background_color",
            field=models.CharField(
                blank=True, default="#FFFFFF", help_text="Couleur de fond", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="body_font",
            field=models.CharField(
                blank=True,
                default="Inter",
                help_text="Police pour le corps de texte",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="body_size",
            field=models.CharField(
                blank=True,
                default="1rem",
                help_text="Taille du texte normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="heading_font",
            field=models.CharField(
                blank=True,
                default="Playfair Display",
                help_text="Police pour les titres",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="heading_size",
            field=models.CharField(
                blank=True,
                default="2.5rem",
                help_text="Taille des titres principaux",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="primary_color",
            field=models.CharField(
                blank=True,
                default="#3B82F6",
                help_text="Couleur principale (hex: #RRGGBB)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="secondary_color",
            field=models.CharField(
                blank=True,
                default="#10B981",
                help_text="Couleur secondaire",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="small_size",
            field=models.CharField(
                blank=True,
                default="0.875rem",
                help_text="Taille du petit texte",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="subheading_size",
            field=models.CharField(
                blank=True,
                default="1.5rem",
                help_text="Taille des sous-titres",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="text_color",
            field=models.CharField(
                blank=True,
                default="#1F2937",
                help_text="Couleur du texte principal",
                max_length=7,
            ),
        ),
    ]
