# Generated by Django 5.0.4 on 2026-01-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0005_add_style_customization"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_contact_title_en",
            field=models.CharField(blank=True, default="Contact Us", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_contact_title_fr",
            field=models.CharField(
                blank=True, default="Contactez-nous", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_contact_title_rn",
            field=models.CharField(blank=True, default="Twandikire", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_contact_title_sw",
            field=models.CharField(
                blank=True, default="Wasiliana Nasi", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_copyright_en",
            field=models.CharField(
                blank=True, default="All rights reserved", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_copyright_fr",
            field=models.CharField(
                blank=True, default="Tous droits réservés", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_copyright_rn",
            field=models.CharField(
                blank=True, default="Uburenganzira bwose", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_copyright_sw",
            field=models.CharField(
                blank=True, default="Haki zote zimehifadhiwa", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_description_en",
            field=models.TextField(
                blank=True,
                default="A Christian ministry focused on inner healing, meditation on God's Word, biblical teaching and personal growth.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_description_fr",
            field=models.TextField(
                blank=True,
                default="Un ministère chrétien centré sur la guérison intérieure, la méditation de la Parole de Dieu, l'enseignement biblique et la croissance personnelle.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_description_rn",
            field=models.TextField(
                blank=True,
                default="Umurimo w'amadini wo gukira mu mutima, gutekereza Ijambo ry'Imana, inyigisho za Bibiliya no gukura.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_description_sw",
            field=models.TextField(
                blank=True,
                default="Huduma ya Kikristo inayolenga uponyaji wa ndani, kutafakari Neno la Mungu, mafundisho ya Biblia na ukuaji binafsi.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_quick_links_title_en",
            field=models.CharField(blank=True, default="Quick Links", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_quick_links_title_fr",
            field=models.CharField(blank=True, default="Liens rapides", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_quick_links_title_rn",
            field=models.CharField(blank=True, default="Amahuza", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_quick_links_title_sw",
            field=models.CharField(
                blank=True, default="Viungo vya Haraka", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_social_title_en",
            field=models.CharField(blank=True, default="Follow Us", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_social_title_fr",
            field=models.CharField(blank=True, default="Suivez-nous", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_social_title_rn",
            field=models.CharField(blank=True, default="Dukurikire", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_social_title_sw",
            field=models.CharField(blank=True, default="Tufuate", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_admin_btn_en",
            field=models.CharField(blank=True, default="Admin Login", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_admin_btn_fr",
            field=models.CharField(
                blank=True,
                default="Connexion Admin",
                help_text="Texte du bouton admin",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_admin_btn_rn",
            field=models.CharField(blank=True, default="Injira Admin", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_admin_btn_sw",
            field=models.CharField(blank=True, default="Ingia Admin", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_slogan_en",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_slogan_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Slogan dans le header",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_slogan_rn",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_slogan_sw",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_admin_button",
            field=models.BooleanField(
                default=True, help_text="Afficher le bouton admin dans le header"
            ),
        ),
    ]
