# Generated by Django 5.0.4 on 2026-01-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0006_add_header_footer_customization"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="page_about_title_en",
            field=models.CharField(blank=True, default="About", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="page_about_title_fr",
            field=models.CharField(
                blank=True,
                default="À propos",
                help_text="Titre de la page À propos",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="page_about_title_rn",
            field=models.CharField(blank=True, default="Ibyerekeye", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="page_about_title_sw",
            field=models.CharField(blank=True, default="Kuhusu", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="page_contact_title_en",
            field=models.CharField(blank=True, default="Contact Us", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="page_contact_title_fr",
            field=models.CharField(
                blank=True,
                default="Contactez-nous",
                help_text="Titre de la page Contact",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="page_contact_title_rn",
            field=models.CharField(blank=True, default="Twandikire", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="page_contact_title_sw",
            field=models.CharField(
                blank=True, default="Wasiliana Nasi", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="page_courses_title_en",
            field=models.CharField(blank=True, default="All Courses", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="page_courses_title_fr",
            field=models.CharField(
                blank=True,
                default="Toutes les émissions",
                help_text="Titre de la page des émissions",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="page_courses_title_rn",
            field=models.CharField(
                blank=True, default="Imitangire yose", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="page_courses_title_sw",
            field=models.CharField(
                blank=True, default="Matangazo Yote", max_length=200
            ),
        ),
    ]
