# Generated by Django 5.0.4 on 2026-02-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0007_add_page_titles"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Image de fond de la section Héro",
                null=True,
                upload_to="settings/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_audience_value",
            field=models.CharField(blank=True, default="8K", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_emissions_value",
            field=models.CharField(blank=True, default="120+", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_languages_value",
            field=models.CharField(blank=True, default="15", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat_languages_fr",
            field=models.CharField(blank=True, default="Thématiques", max_length=50),
        ),
    ]
