# Generated by Django 5.0.4 on 2026-02-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0008_sitesettings_hero_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_badge_en",
            field=models.CharField(blank=True, default="About Us", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_badge_fr",
            field=models.CharField(blank=True, default="À Propos", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_badge_rn",
            field=models.CharField(blank=True, default="Ibitwerekeye", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_badge_sw",
            field=models.CharField(blank=True, default="Kuhusu Sisi", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title_accent_en",
            field=models.CharField(blank=True, default="& Vision", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title_accent_fr",
            field=models.CharField(blank=True, default="& Vision", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title_accent_rn",
            field=models.CharField(blank=True, default="& Vision", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title_accent_sw",
            field=models.CharField(blank=True, default="& Maono", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title_en",
            field=models.CharField(blank=True, default="Our Story", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title_fr",
            field=models.CharField(
                blank=True, default="Notre Histoire", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title_rn",
            field=models.CharField(blank=True, default="Amateka yacu", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title_sw",
            field=models.CharField(blank=True, default="Historia yetu", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_badge_en",
            field=models.CharField(blank=True, default="Contact", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_badge_fr",
            field=models.CharField(blank=True, default="Contact", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_badge_rn",
            field=models.CharField(blank=True, default="Twandikire", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_badge_sw",
            field=models.CharField(
                blank=True, default="Wasiliana Nasi", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_accent_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_accent_fr",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_accent_rn",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_accent_sw",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_badge_en",
            field=models.CharField(blank=True, default="Announcements", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_badge_fr",
            field=models.CharField(blank=True, default="Annonces", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_badge_rn",
            field=models.CharField(blank=True, default="Imitangire", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_badge_sw",
            field=models.CharField(blank=True, default="Matangazo", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_desc_en",
            field=models.TextField(
                blank=True, default="Stay informed about our ministry activities"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_desc_fr",
            field=models.TextField(
                blank=True, default="Restez informé des activités de notre ministère"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_desc_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_desc_sw",
            field=models.TextField(
                blank=True, default="Pata habari kuhusu shughuli za huduma yetu"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_title_en",
            field=models.CharField(blank=True, default="Info & Events", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_title_fr",
            field=models.CharField(
                blank=True, default="Infos & Événements", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_title_rn",
            field=models.CharField(blank=True, default="Amakuru", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_announcements_title_sw",
            field=models.CharField(
                blank=True, default="Habari na Matukio", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_categories_accent_en",
            field=models.CharField(blank=True, default="Programs", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_categories_accent_fr",
            field=models.CharField(blank=True, default="Emissions", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_categories_accent_rn",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_categories_accent_sw",
            field=models.CharField(blank=True, default="Matangazo", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_accent_en",
            field=models.CharField(blank=True, default="Videos", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_accent_fr",
            field=models.CharField(blank=True, default="Vidéos", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_accent_rn",
            field=models.CharField(blank=True, default="Vidéos", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_accent_sw",
            field=models.CharField(blank=True, default="Video", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_badge_en",
            field=models.CharField(blank=True, default="New Content", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_badge_fr",
            field=models.CharField(blank=True, default="Nouveauté", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_badge_rn",
            field=models.CharField(blank=True, default="Gishasha", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_badge_sw",
            field=models.CharField(blank=True, default="Mpya", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_desc_en",
            field=models.TextField(
                blank=True, default="Discover our latest productions"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_desc_fr",
            field=models.TextField(
                blank=True, default="Découvrez nos dernières productions"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_desc_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_featured_desc_sw",
            field=models.TextField(
                blank=True, default="Gundua kazi zetu za hivi punde"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_accent_en",
            field=models.CharField(blank=True, default="about us", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_accent_fr",
            field=models.CharField(blank=True, default="de nous", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_accent_rn",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_accent_sw",
            field=models.CharField(blank=True, default="kuhusu sisi", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_badge_en",
            field=models.CharField(blank=True, default="Testimonials", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_badge_fr",
            field=models.CharField(blank=True, default="Témoignages", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_badge_rn",
            field=models.CharField(blank=True, default="Ivyerekeye", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_badge_sw",
            field=models.CharField(blank=True, default="Ushuhuda", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_desc_en",
            field=models.TextField(
                blank=True, default="Discover how Shalom Ministry transforms lives"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_desc_fr",
            field=models.TextField(
                blank=True,
                default="Découvrez comment Shalom Ministry transforme des vies",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_desc_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_desc_sw",
            field=models.TextField(
                blank=True,
                default="Gundua jinsi Shalom Ministry inavyobadilisha maisha",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_title_en",
            field=models.CharField(
                blank=True, default="What people say", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_title_fr",
            field=models.CharField(
                blank=True, default="Ce qu'ils disent", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_title_rn",
            field=models.CharField(blank=True, default="Ico bavuga", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_testimonials_title_sw",
            field=models.CharField(blank=True, default="Wanachosema", max_length=200),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_rn",
            field=models.CharField(
                blank=True, default="Kurira mu kwizera", max_length=200
            ),
        ),
    ]
