# Generated by Django 5.0.4 on 2026-02-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0009_sitesettings_about_badge_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature1_title_en",
            field=models.CharField(
                blank=True, default="Biblical Teachings", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature1_title_fr",
            field=models.CharField(
                blank=True, default="Enseignements Bibliques", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature1_title_rn",
            field=models.CharField(
                blank=True, default="Inyigisho za Bibiliya", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature1_title_sw",
            field=models.CharField(
                blank=True, default="Mafundisho ya Biblia", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature2_title_en",
            field=models.CharField(blank=True, default="Heart Healing", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature2_title_fr",
            field=models.CharField(
                blank=True, default="Guérison du Cœur", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature2_title_rn",
            field=models.CharField(
                blank=True, default="Gukira mu mutima", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature2_title_sw",
            field=models.CharField(
                blank=True, default="Uponyaji wa Moyo", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature3_title_en",
            field=models.CharField(
                blank=True, default="Spiritual Awakening", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature3_title_fr",
            field=models.CharField(
                blank=True, default="Réveil Spirituel", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature3_title_rn",
            field=models.CharField(
                blank=True, default="Gukura mu mpwemu", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature3_title_sw",
            field=models.CharField(
                blank=True, default="Uamsho wa Kiroho", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature4_title_en",
            field=models.CharField(
                blank=True, default="Our Commitments", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature4_title_fr",
            field=models.CharField(
                blank=True, default="Nos Engagements", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature4_title_rn",
            field=models.CharField(blank=True, default="Ivyo wipfuza", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature4_title_sw",
            field=models.CharField(blank=True, default="Ahadi Zetu", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_image",
            field=models.ImageField(
                blank=True,
                help_text="Image principale section À Propos",
                null=True,
                upload_to="settings/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_author_image",
            field=models.ImageField(
                blank=True,
                help_text="Photo de l'auteur de la citation (Pasteur)",
                null=True,
                upload_to="settings/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_author_name_en",
            field=models.CharField(blank=True, default="Pastor", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_author_name_fr",
            field=models.CharField(blank=True, default="Pasteur", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_author_name_rn",
            field=models.CharField(blank=True, default="Umupasitori", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_author_name_sw",
            field=models.CharField(blank=True, default="Mchungaji", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_author_subtitle_en",
            field=models.CharField(blank=True, default="Senior Pastor", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_author_subtitle_fr",
            field=models.CharField(
                blank=True, default="Pasteur Principal", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_author_subtitle_rn",
            field=models.CharField(
                blank=True, default="Umupasitori mukuru", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_author_subtitle_sw",
            field=models.CharField(
                blank=True, default="Mchungaji Mkuu", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_text_en",
            field=models.TextField(
                blank=True,
                default="The Word of God is not just a story, it is a power that recreates the soul.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_text_fr",
            field=models.TextField(
                blank=True,
                default="La Parole de Dieu n'est pas seulement un récit, c'est une puissance qui recrée l'âme.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_text_rn",
            field=models.TextField(
                blank=True,
                default="Ijambo ry'Imana si inkuru gusa, n'ububasha buvugurura impwemu.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_text_sw",
            field=models.TextField(
                blank=True,
                default="Neno la Mungu sio hadithi tu, ni nguvu inayoumbwa upya nafsi.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_years_label_en",
            field=models.CharField(
                blank=True, default="Years of Ministry", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_years_label_fr",
            field=models.CharField(
                blank=True, default="Années de Ministère", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_years_label_rn",
            field=models.CharField(
                blank=True, default="Imyaka ya ministeri", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_years_label_sw",
            field=models.CharField(
                blank=True, default="Miaka ya Huduma", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_years_value",
            field=models.CharField(blank=True, default="10+", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_description_en",
            field=models.TextField(
                blank=True, default="A dedicated team to accompany you."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_description_fr",
            field=models.TextField(
                blank=True, default="Une équipe dévouée pour vous accompagner."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_description_rn",
            field=models.TextField(
                blank=True, default="Umurwi witangiye gukorera Ubwami."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_description_sw",
            field=models.TextField(
                blank=True, default="Timu iliyojitolea kuandamana nawe."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_image",
            field=models.ImageField(
                blank=True,
                help_text="Image de l'équipe",
                null=True,
                upload_to="settings/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_title_en",
            field=models.CharField(blank=True, default="Our Team", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_title_fr",
            field=models.CharField(blank=True, default="Notre Équipe", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_title_rn",
            field=models.CharField(blank=True, default="Umurwi wacu", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_title_sw",
            field=models.CharField(blank=True, default="Timu Yetu", max_length=200),
        ),
    ]
