# Generated by Django 5.0.4 on 2026-02-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0010_sitesettings_about_feature1_title_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature1_title_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature1_title_fr",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature1_title_rn",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature1_title_sw",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature2_title_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature2_title_fr",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature2_title_rn",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature2_title_sw",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature3_title_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature3_title_fr",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature3_title_rn",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature3_title_sw",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature4_title_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature4_title_fr",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature4_title_rn",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_feature4_title_sw",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature1_en",
            field=models.CharField(
                blank=True, default="Biblical Teaching", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature1_fr",
            field=models.CharField(
                blank=True, default="Enseignement Biblique", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature1_rn",
            field=models.CharField(
                blank=True, default="Inyigisho za Bibiliya", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature1_sw",
            field=models.CharField(
                blank=True, default="Mafundisho ya Biblia", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature2_en",
            field=models.CharField(blank=True, default="Heart Healing", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature2_fr",
            field=models.CharField(
                blank=True, default="Guérison du Cœur", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature2_rn",
            field=models.CharField(
                blank=True, default="Gukiza Umutima", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature2_sw",
            field=models.CharField(
                blank=True, default="Uponyaji wa Moyo", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature3_en",
            field=models.CharField(
                blank=True, default="Spiritual Awakening", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature3_fr",
            field=models.CharField(
                blank=True, default="Éveil Spirituel", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature3_rn",
            field=models.CharField(
                blank=True, default="Ikangura ry'Umutima", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature3_sw",
            field=models.CharField(
                blank=True, default="Uamsho wa Kiroho", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature4_en",
            field=models.CharField(
                blank=True, default="Our Commitments", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature4_fr",
            field=models.CharField(
                blank=True, default="Nos Engagements", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature4_rn",
            field=models.CharField(
                blank=True, default="Ibikorwa vyacu", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_feature4_sw",
            field=models.CharField(blank=True, default="Ahadi Zetu", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="about_image",
            field=models.ImageField(
                blank=True,
                help_text="Image de la section À Propos (ex: église)",
                null=True,
                upload_to="settings/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_image",
            field=models.ImageField(
                blank=True,
                help_text="Photo du pasteur pour la citation",
                null=True,
                upload_to="settings/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_name_en",
            field=models.CharField(blank=True, default="Senior Pastor", max_length=200),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_name_fr",
            field=models.CharField(
                blank=True, default="Pasteur Principal", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_name_rn",
            field=models.CharField(
                blank=True, default="Umupasitori Mukuru", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_name_sw",
            field=models.CharField(
                blank=True, default="Mchungaji Mkuu", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_subtitle_en",
            field=models.CharField(
                blank=True, default="Shalom Ministry", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_subtitle_fr",
            field=models.CharField(
                blank=True, default="Shalom Ministry", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_subtitle_rn",
            field=models.CharField(
                blank=True, default="Shalom Ministry", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_subtitle_sw",
            field=models.CharField(
                blank=True, default="Shalom Ministry", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_text_en",
            field=models.TextField(
                blank=True,
                default="The Word of God is not just a story, it is a power that recreates the soul and aligns the spirit.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_text_fr",
            field=models.TextField(
                blank=True,
                default="La Parole de Dieu n'est pas seulement un récit, c'est une puissance qui recrée l'âme et aligne l'esprit.",
                help_text="Citation du pasteur",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_text_rn",
            field=models.TextField(
                blank=True,
                default="Ijambo ry'Imana si inkuru gusa, ni ububasha bwongera kubumba ubugingo bukagorora umutima.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_text_sw",
            field=models.TextField(
                blank=True,
                default="Neno la Mungu si hadithi tu, ni nguvu inayoumba upya nafsi na kunyoosha roho.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat_years_label_en",
            field=models.CharField(
                blank=True, default="Years of Service", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat_years_label_fr",
            field=models.CharField(
                blank=True, default="Années de service", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat_years_label_rn",
            field=models.CharField(
                blank=True, default="Imyaka y'umurimo", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat_years_label_sw",
            field=models.CharField(
                blank=True, default="Miaka ya Huduma", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat_years_value",
            field=models.CharField(
                blank=True,
                default="10+",
                help_text="Nombre d'années de service",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="team_description_en",
            field=models.TextField(
                blank=True,
                default="A team dedicated to serving the Kingdom to accompany you in your Christian journey.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="team_description_fr",
            field=models.TextField(
                blank=True,
                default="Une équipe dévouée au service du Royaume pour vous accompagner dans votre parcours chrétien.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="team_description_rn",
            field=models.TextField(
                blank=True,
                default="Umurwi utizigira gukora igikorwa c'Ubwami kugira ngo ugufatanye mu rugendo rwawe rw'ubukirisu.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="team_description_sw",
            field=models.TextField(
                blank=True,
                default="Timu iliyojitolea kutumikia Ufalme ili kukufuatana katika safari yako ya Kikristo.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="team_image",
            field=models.ImageField(
                blank=True,
                help_text="Photo de l'équipe",
                null=True,
                upload_to="settings/",
            ),
        ),
    ]
