# Generated by Django 5.0.4 on 2026-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0011_remove_sitesettings_about_feature1_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="bishop_bio_p1_fr",
            field=models.TextField(
                blank=True,
                default="Ordonné prêtre en 1995, Mgr Samuel Nduwayo a consacré sa vie au service de l'Église...",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bishop_bio_p2_fr",
            field=models.TextField(
                blank=True,
                default="Sa vision d'une Église engagée socialement a permis le développement de projets...",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="diocese_subtitle_fr",
            field=models.TextField(
                blank=True,
                default="L'Église Anglicane du Diocèse de Makamba, fondée en 2009, est un pilier spirituel et social de la province de Makamba au Burundi.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="history_intro_text_fr",
            field=models.TextField(
                blank=True,
                default="L'histoire de l'anglicanisme au Burundi remonte aux premières missions...",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="history_intro_title_fr",
            field=models.CharField(blank=True, default="Les origines", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="history_subtitle_fr",
            field=models.TextField(
                blank=True,
                default="Des origines missionnaires à un diocèse enraciné au cœur de Makamba.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_intro_fr",
            field=models.TextField(
                blank=True,
                default="Le diocèse de Makamba s'engage à travers six axes missionnels complémentaires :",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_subtitle_fr",
            field=models.TextField(
                blank=True,
                default="Notre boussole spirituelle et notre engagement concret au service des communautés de Makamba.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_text_fr",
            field=models.TextField(
                blank=True,
                default="« Être une Église vivante, ancrée dans l'Évangile... »",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat_years_value",
            field=models.CharField(blank=True, default="25+", max_length=50),
        ),
    ]
