# Generated by Django 5.0.4 on 2026-02-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0012_sitesettings_bishop_bio_p1_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="engage_description_fr",
            field=models.TextField(
                blank=True,
                default="Chacun a un rôle à jouer dans la mission de notre Église",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_cta_fr",
            field=models.CharField(
                blank=True, default="Découvrir les ministères", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_desc_fr",
            field=models.TextField(
                blank=True,
                default="Jeunes, femmes, éducation… Trouvez votre place dans la vie du diocèse.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_href",
            field=models.CharField(blank=True, default="/ministeres", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_icon",
            field=models.CharField(blank=True, default="Users", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_title_fr",
            field=models.CharField(
                blank=True, default="Rejoindre un ministère", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_cta_fr",
            field=models.CharField(blank=True, default="Faire un don", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_desc_fr",
            field=models.TextField(
                blank=True,
                default="Participez au financement de nos projets d'éducation, santé et développement.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_href",
            field=models.CharField(blank=True, default="/contact", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_icon",
            field=models.CharField(blank=True, default="HandHeart", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_title_fr",
            field=models.CharField(
                blank=True, default="Soutenir un projet", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_cta_fr",
            field=models.CharField(blank=True, default="Voir l'agenda", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_desc_fr",
            field=models.TextField(
                blank=True,
                default="Rejoignez nos groupes de prière, retraites spirituelles et célébrations.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_href",
            field=models.CharField(blank=True, default="/actualites", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_icon",
            field=models.CharField(blank=True, default="BookOpen", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_title_fr",
            field=models.CharField(
                blank=True, default="Participer à la prière", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_title_fr",
            field=models.CharField(
                blank=True, default="S'engager avec le diocèse", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_description_fr",
            field=models.TextField(
                blank=True,
                default="Le diocèse de Makamba compte une vingtaine de paroisses réparties dans toute la province...",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_map_stats_fr",
            field=models.CharField(
                blank=True, default="20 paroisses • 8 communes", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_map_subtitle_fr",
            field=models.CharField(
                blank=True, default="Burundi, Afrique de l'Est", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_map_title_fr",
            field=models.CharField(
                blank=True, default="Province de Makamba", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_title_fr",
            field=models.CharField(blank=True, default="Nos paroisses", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_description_fr",
            field=models.TextField(
                blank=True,
                default="Fondé sur l'Évangile, le Diocèse de Makamba s'engage à servir Dieu et les communautés à travers trois piliers fondamentaux.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar1_desc_fr",
            field=models.TextField(
                blank=True,
                default="Une vie sacramentelle riche, ancrée dans la liturgie anglicane et la prière communautaire au quotidien.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar1_icon",
            field=models.CharField(blank=True, default="Cross", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar1_title_fr",
            field=models.CharField(blank=True, default="Foi vivante", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar2_desc_fr",
            field=models.TextField(
                blank=True,
                default="Des paroisses proches des communautés, avec des équipes engagées issues du terroir de Makamba.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar2_icon",
            field=models.CharField(blank=True, default="MapPin", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar2_title_fr",
            field=models.CharField(
                blank=True, default="Enracinement local", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar3_desc_fr",
            field=models.TextField(
                blank=True,
                default="Éducation, santé et développement communautaire : agir concrètement pour transformer les vies.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar3_icon",
            field=models.CharField(blank=True, default="Lightbulb", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar3_title_fr",
            field=models.CharField(
                blank=True, default="Engagement social", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_title_fr",
            field=models.CharField(
                blank=True, default="Notre vision et notre mission", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_address",
            field=models.TextField(blank=True, default="Makamba, Burundi"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="info@makamba-diocese.org", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_phone",
            field=models.CharField(
                blank=True, default="+257 22 23 45 67", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="description",
            field=models.TextField(
                blank=True,
                default="Site officiel du Diocèse Anglicane de Makamba Connect",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_name_en",
            field=models.CharField(
                blank=True, default="Rt. Rev. Samuel Nduwayo", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_name_fr",
            field=models.CharField(
                blank=True, default="Mgr Samuel Nduwayo", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_name_rn",
            field=models.CharField(
                blank=True, default="Mgr Samuel Nduwayo", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_name_sw",
            field=models.CharField(
                blank=True, default="Askofu Samuel Nduwayo", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_subtitle_en",
            field=models.CharField(
                blank=True, default="Bishop of Makamba Diocese", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_subtitle_fr",
            field=models.CharField(
                blank=True, default="Évêque du Diocèse de Makamba", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_subtitle_rn",
            field=models.CharField(
                blank=True, default="Umwepiskopi wa Diyoseze ya Makamba", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_author_subtitle_sw",
            field=models.CharField(
                blank=True, default="Askofu wa Jimbo la Makamba", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_text_fr",
            field=models.TextField(
                blank=True,
                default="La Parole de Dieu est une puissance qui transforme les vies et bâtit les communautés.",
                help_text="Citation de l'Évêque",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="quote_text_sw",
            field=models.TextField(
                blank=True,
                default="Neno la Mungu ni nguvu inayobadilisha maisha na kujenga jamii.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(
                default="Diocèse Anglicane de Makamba", max_length=200
            ),
        ),
    ]
