# Generated by Django 5.0.4 on 2026-02-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0013_sitesettings_engage_description_fr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_title_rn",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_description_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_description_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_cta_en",
            field=models.CharField(
                blank=True, default="Discover ministries", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_cta_rn",
            field=models.CharField(
                blank=True, default="Kumenya ubusuku", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_cta_sw",
            field=models.CharField(blank=True, default="Gundua huduma", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_desc_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_desc_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_desc_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_title_en",
            field=models.CharField(
                blank=True, default="Join a ministry", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_title_rn",
            field=models.CharField(
                blank=True, default="Kwinjira mu busuku", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item1_title_sw",
            field=models.CharField(
                blank=True, default="Jiunge na huduma", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_cta_en",
            field=models.CharField(
                blank=True, default="Make a donation", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_cta_rn",
            field=models.CharField(
                blank=True, default="Gutanga intererano", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_cta_sw",
            field=models.CharField(blank=True, default="Toa msaada", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_desc_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_desc_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_desc_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_title_en",
            field=models.CharField(
                blank=True, default="Support a project", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_title_rn",
            field=models.CharField(
                blank=True, default="Gushigikira umugambi", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item2_title_sw",
            field=models.CharField(blank=True, default="Saidia mradi", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_cta_en",
            field=models.CharField(blank=True, default="See calendar", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_cta_rn",
            field=models.CharField(blank=True, default="Raba gahunda", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_cta_sw",
            field=models.CharField(
                blank=True, default="Angalia kalenda", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_desc_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_desc_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_desc_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_title_en",
            field=models.CharField(
                blank=True, default="Participate in prayer", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_title_rn",
            field=models.CharField(blank=True, default="Gusenga hamwe", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_item3_title_sw",
            field=models.CharField(
                blank=True, default="Shiriki katika maombi", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_title_en",
            field=models.CharField(
                blank=True, default="Engage with the Diocese", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_title_rn",
            field=models.CharField(
                blank=True, default="Gukorana na Diyoseze", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="engage_title_sw",
            field=models.CharField(
                blank=True, default="Shiriki na Jimbo", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_description_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_description_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_map_stats_en",
            field=models.CharField(
                blank=True, default="20 parishes • 8 communes", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_map_stats_rn",
            field=models.CharField(
                blank=True, default="Ibishengero 20 • Ikomine 8", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_map_stats_sw",
            field=models.CharField(
                blank=True, default="Parokia 20 • Komini 8", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_map_subtitle_en",
            field=models.CharField(
                blank=True, default="Burundi, East Africa", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_map_subtitle_rn",
            field=models.CharField(
                blank=True, default="Uburundi, Afrika y'ubuseruko", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_map_subtitle_sw",
            field=models.CharField(
                blank=True, default="Burundi, Afrika Mashariki", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_map_title_en",
            field=models.CharField(
                blank=True, default="Makamba Province", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_map_title_rn",
            field=models.CharField(
                blank=True, default="Intara ya Makamba", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_map_title_sw",
            field=models.CharField(
                blank=True, default="Mkoa wa Makamba", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_title_en",
            field=models.CharField(blank=True, default="Our Parishes", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_title_rn",
            field=models.CharField(
                blank=True, default="Ibishengero vyacu", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_title_sw",
            field=models.CharField(blank=True, default="Parokia Zetu", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_description_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_description_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar1_desc_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar1_desc_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar1_desc_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar1_title_en",
            field=models.CharField(blank=True, default="Living Faith", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar1_title_rn",
            field=models.CharField(
                blank=True, default="Ukwizera kuzima", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar1_title_sw",
            field=models.CharField(blank=True, default="Imani Hai", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar2_desc_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar2_desc_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar2_desc_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar2_title_en",
            field=models.CharField(blank=True, default="Local Rooting", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar2_title_rn",
            field=models.CharField(
                blank=True, default="Gushinga imizi aho turi", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar2_title_sw",
            field=models.CharField(
                blank=True, default="Kushika Mizizi", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar3_desc_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar3_desc_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar3_desc_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar3_title_en",
            field=models.CharField(
                blank=True, default="Social Engagement", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar3_title_rn",
            field=models.CharField(
                blank=True, default="Gufatanya n’abanyagihugu", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_pillar3_title_sw",
            field=models.CharField(
                blank=True, default="Kujitolea kwa Jamii", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_title_en",
            field=models.CharField(
                blank=True, default="Our Vision and Mission", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_title_rn",
            field=models.CharField(
                blank=True, default="Ivyo twiyemeje n’irangamana ryacu", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_title_sw",
            field=models.CharField(
                blank=True, default="Maono na Utume Wetu", max_length=200
            ),
        ),
    ]
