# Generated by Django 5.0.4 on 2026-02-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0014_remove_sitesettings_hero_title_rn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_title_rn",
            field=models.CharField(
                blank=True, default="Gukura mu kwizera", max_length=200
            ),
        ),
    ]
