# Generated by Django 5.0.4 on 2026-03-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0015_sitesettings_hero_title_rn"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="engage_bg_image",
            field=models.ImageField(
                blank=True,
                help_text="Image de fond section Engagement",
                null=True,
                upload_to="settings/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_brand_name",
            field=models.CharField(
                blank=True, default="Diocèse de Makamba", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_brand_subtitle",
            field=models.CharField(
                blank=True,
                default="Église Anglicane du Burundi. Servir Dieu et notre prochain au cœur de Makamba.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_bg_image",
            field=models.ImageField(
                blank=True,
                help_text="Image de fond section Paroisses",
                null=True,
                upload_to="settings/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_audience_desc_en",
            field=models.CharField(
                blank=True, default="Global audience", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_audience_desc_fr",
            field=models.CharField(
                blank=True, default="Audience globale", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_audience_desc_rn",
            field=models.CharField(blank=True, default="Abatega bose", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_audience_desc_sw",
            field=models.CharField(
                blank=True, default="Watazamaji wote", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_emissions_desc_en",
            field=models.CharField(blank=True, default="Broadcast", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_emissions_desc_fr",
            field=models.CharField(blank=True, default="Diffusées", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_emissions_desc_rn",
            field=models.CharField(blank=True, default="Zasabwe", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_emissions_desc_sw",
            field=models.CharField(blank=True, default="Zimetangazwa", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_languages_desc_en",
            field=models.CharField(blank=True, default="Covered", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_languages_desc_fr",
            field=models.CharField(blank=True, default="Abordées", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_languages_desc_rn",
            field=models.CharField(blank=True, default="Zishikirijwe", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_languages_desc_sw",
            field=models.CharField(blank=True, default="Zimefunikwa", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_years_desc_en",
            field=models.CharField(blank=True, default="serving God", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_years_desc_fr",
            field=models.CharField(
                blank=True, default="au service de Dieu", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_years_desc_rn",
            field=models.CharField(
                blank=True, default="mu gikorwa c'Imana", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_years_desc_sw",
            field=models.CharField(
                blank=True, default="katika huduma ya Mungu", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stats_cta_href",
            field=models.CharField(blank=True, default="/diocese", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stats_cta_link_text_en",
            field=models.CharField(blank=True, default="Learn more", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stats_cta_link_text_fr",
            field=models.CharField(
                blank=True, default="En savoir plus", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stats_cta_link_text_rn",
            field=models.CharField(blank=True, default="Ibindi", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stats_cta_link_text_sw",
            field=models.CharField(blank=True, default="Soma zaidi", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stats_cta_title_en",
            field=models.CharField(
                blank=True, default="Discover the diocese", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stats_cta_title_fr",
            field=models.CharField(
                blank=True, default="Découvrir le diocèse", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stats_cta_title_rn",
            field=models.CharField(
                blank=True, default="Kumenya diyoseze", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stats_cta_title_sw",
            field=models.CharField(blank=True, default="Gundua jimbo", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stories_badge_en",
            field=models.CharField(blank=True, default="On the ground", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stories_badge_fr",
            field=models.CharField(
                blank=True, default="Sur le terrain", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stories_badge_rn",
            field=models.CharField(blank=True, default="Ku kibanza", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stories_badge_sw",
            field=models.CharField(blank=True, default="Uwanjani", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stories_bg_image",
            field=models.ImageField(
                blank=True,
                help_text="Image de fond section Actualités",
                null=True,
                upload_to="settings/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stories_title_en",
            field=models.CharField(
                blank=True, default="All the latest from our actions", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stories_title_fr",
            field=models.CharField(
                blank=True, default="Toute l'actualité de nos actions", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stories_title_rn",
            field=models.CharField(
                blank=True, default="Amakuru yose y'ibikorwa vyacu", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stories_title_sw",
            field=models.CharField(
                blank=True, default="Habari zote za vitendo vyetu", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_bg_image",
            field=models.ImageField(
                blank=True,
                help_text="Image de fond section Vision",
                null=True,
                upload_to="settings/",
            ),
        ),
    ]
