# Generated by Django 5.0.4 on 2026-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0016_sitesettings_engage_bg_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_badge_en",
            field=models.CharField(
                blank=True, default="ANGELICAN CHURCH OF BURUNDI", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_badge_fr",
            field=models.CharField(
                blank=True, default="KANISA LA ANGLIKANA BURUNDI", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_badge_rn",
            field=models.CharField(
                blank=True, default="KANISA LA ANGLIKANA BURUNDI", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_badge_sw",
            field=models.CharField(
                blank=True, default="KANISA LA ANGLIKANA BURUNDI", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn1_link_en",
            field=models.CharField(blank=True, default="/diocese", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn1_link_fr",
            field=models.CharField(blank=True, default="/diocese", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn1_link_rn",
            field=models.CharField(blank=True, default="/diocese", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn1_link_sw",
            field=models.CharField(blank=True, default="/diocese", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn1_text_en",
            field=models.CharField(
                blank=True, default="Discover the diocese", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn1_text_fr",
            field=models.CharField(
                blank=True, default="Gundua diyosisi", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn1_text_rn",
            field=models.CharField(
                blank=True, default="Gundua diyosisi", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn1_text_sw",
            field=models.CharField(
                blank=True, default="Gundua diyosisi", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn2_link_en",
            field=models.CharField(blank=True, default="/ministeres", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn2_link_fr",
            field=models.CharField(blank=True, default="/ministeres", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn2_link_rn",
            field=models.CharField(blank=True, default="/ministeres", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn2_link_sw",
            field=models.CharField(blank=True, default="/ministeres", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn2_text_en",
            field=models.CharField(blank=True, default="Diocese Life", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn2_text_fr",
            field=models.CharField(
                blank=True, default="Maisha ya diyosisi", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn2_text_rn",
            field=models.CharField(
                blank=True, default="Maisha ya diyosisi", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn2_text_sw",
            field=models.CharField(
                blank=True, default="Maisha ya diyosisi", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_subtitle_en",
            field=models.TextField(
                blank=True,
                default="Serving God and our neighbor in the heart of Makamba.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_subtitle_fr",
            field=models.TextField(
                blank=True,
                default="Servir Dieu et notre prochain au cœur de Makamba. Annoncer l'Évangile, bâtir la paix, promouvoir l'éducation et la solidarité.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_subtitle_rn",
            field=models.TextField(
                blank=True, default="Servir Dieu et notre prochain au cœur de Makamba."
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_subtitle_sw",
            field=models.TextField(
                blank=True, default="Servir Dieu et notre prochain au cœur de Makamba."
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_en",
            field=models.CharField(
                blank=True, default="Makamba Diocese", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_fr",
            field=models.CharField(
                blank=True, default="Diocèse de Makamba", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_rn",
            field=models.CharField(
                blank=True, default="Diocèse de Makamba", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_sw",
            field=models.CharField(
                blank=True, default="Jimbo la Makamba", max_length=200
            ),
        ),
    ]
