# Generated by Django 5.0.4 on 2026-03-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0017_sitesettings_hero_badge_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="default_language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("rn", "Kirundi"),
                    ("en", "English"),
                    ("sw", "Swahili"),
                ],
                default="fr",
                help_text="Langue par défaut du site",
                max_length=2,
            ),
        ),
    ]
