# Generated by Django 5.0.4 on 2026-03-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0018_sitesettings_default_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="about_content_fr",
            field=models.TextField(
                blank=True,
                default="Bienvenue sur le site du Diocese Makamba, une communauté dédiée à la croissance spirituelle.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="description",
            field=models.TextField(
                blank=True, default="Site officiel du Diocese Makamba Connect"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="engage_description_en",
            field=models.TextField(
                blank=True,
                default="Everyone has a role to play in the mission of our Church",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="engage_description_rn",
            field=models.TextField(
                blank=True,
                default="Umwe wese afise uruhara mu gikorwa c'Ishengero ryacu",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="engage_description_sw",
            field=models.TextField(
                blank=True,
                default="Kila mmoja ana jukumu la kutoa katika misheni ya Kanisa letu",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="engage_item1_desc_en",
            field=models.TextField(
                blank=True,
                default="Youth, women, education… Find your place in the life of the diocese.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="engage_item1_desc_rn",
            field=models.TextField(
                blank=True,
                default="Uwaruka, abakenyezi, inyigisho... Rondera ikibanza cawe mu buzima bwa diyoseze.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="engage_item1_desc_sw",
            field=models.TextField(
                blank=True,
                default="Vijana, wanawake, elimu... Pata nafasi yako katika maisha ya jimbo.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="engage_item2_desc_en",
            field=models.TextField(
                blank=True,
                default="Participate in funding our education, health, and development projects.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="engage_item2_desc_rn",
            field=models.TextField(
                blank=True,
                default="Tabara mu gushira mu ngiro imigambi y'inyigisho, amagara y'abantu n'iterambere.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="engage_item2_desc_sw",
            field=models.TextField(
                blank=True,
                default="Shiriki katika kufadhili miradi yetu ya elimu, afya, na maendeleo.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="engage_item3_desc_en",
            field=models.TextField(
                blank=True,
                default="Join our prayer groups, spiritual retreats, and celebrations.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="engage_item3_desc_rn",
            field=models.TextField(
                blank=True,
                default="Injira mu mirwi y'isengesho, mu bihe vyo kwisanzura no mu birori.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="engage_item3_desc_sw",
            field=models.TextField(
                blank=True,
                default="Jiunge na vikundi vyetu vya maombi, mapumziko ya kiroho, na sherehe.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_badge_fr",
            field=models.CharField(
                blank=True, default="ÉGLISE ANGLICANE DU BURUNDI", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_badge_rn",
            field=models.CharField(
                blank=True, default="ISHENGERO RYA ANGLIKANA MU BURUNDI", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="section_testimonials_desc_en",
            field=models.TextField(
                blank=True, default="Discover how Diocese Makamba transforms lives"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="section_testimonials_desc_fr",
            field=models.TextField(
                blank=True,
                default="Découvrez comment le Diocese Makamba transforme des vies",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="section_testimonials_desc_sw",
            field=models.TextField(
                blank=True,
                default="Gundua jinsi Diocese Makamba inavyobadilisha maisha",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="Diocese Makamba", max_length=200),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vision_description_en",
            field=models.TextField(
                blank=True,
                default="Rooted in the Gospel, the Diocese of Makamba is committed to serving God and communities through three fundamental pillars.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vision_description_rn",
            field=models.TextField(
                blank=True,
                default="Diyoseze ya Makamba ishingiye ku Njili, yiyemeje gukorera Imana n'abanyagihugu biciye mu nkingi zitatu zishinze.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vision_description_sw",
            field=models.TextField(
                blank=True,
                default="Likizikwa katika Injili, Jimbo la Makamba limejitolea kumtumikia Mungu na jamii kupitia nguzo tatu za msingi.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vision_pillar1_desc_en",
            field=models.TextField(
                blank=True,
                default="A rich sacramental life, rooted in Anglican liturgy and daily community prayer.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vision_pillar1_desc_rn",
            field=models.TextField(
                blank=True,
                default="Ubuzima bw'amasakaramentu butunze, bushingiye kuri liturujiya ya Anglikana n'isengesho ry'ishengero rya buri musi.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vision_pillar1_desc_sw",
            field=models.TextField(
                blank=True,
                default="Maisha tajiri ya kisakramenti, yaliyozikwa katika liturujia ya Kianglikana na sala ya kila siku ya jamii.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vision_pillar2_desc_en",
            field=models.TextField(
                blank=True,
                default="Parishes close to communities, with dedicated teams from the local Makamba area.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vision_pillar2_desc_rn",
            field=models.TextField(
                blank=True,
                default="Ibishengero biri hafi y'abanyagihugu, birimwo imirwi ikuye amaboko mu mufuko ikomoka mu ntara ya Makamba.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vision_pillar2_desc_sw",
            field=models.TextField(
                blank=True,
                default="Parokia zilizo karibu na jamii, zikiwa na timu zilizojitolea kutoka eneo la Makamba.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vision_pillar3_desc_en",
            field=models.TextField(
                blank=True,
                default="Education, health and community development: concrete action to transform lives.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vision_pillar3_desc_rn",
            field=models.TextField(
                blank=True,
                default="Inyigisho, amagara y'abantu n'iterambere ry'abanyagihugu: gukora ibintu biboneka kugira ngo ubuzima bwahinduke.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vision_pillar3_desc_sw",
            field=models.TextField(
                blank=True,
                default="Elimu, afya na maendeleo ya jamii: kuchukua hatua thabiti kubadilisha maisha.",
            ),
        ),
    ]
