# Generated by Django 5.0.4 on 2026-03-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0019_alter_sitesettings_about_content_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_badge_en",
            field=models.CharField(
                blank=True, default="DISCOVER THE DIOCESE", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_badge_fr",
            field=models.CharField(
                blank=True, default="DÉCOUVRIR LE DIOCÈSE", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_badge_rn",
            field=models.CharField(
                blank=True, default="KUMENYA DIYOSEZE", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parishes_badge_sw",
            field=models.CharField(blank=True, default="GUNDUA JIMBO", max_length=150),
        ),
    ]
