# Generated by Django 5.0.4 on 2026-03-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0020_sitesettings_parishes_badge_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="diocese_subtitle_en",
            field=models.TextField(
                blank=True,
                default="The Anglican Church of Makamba Diocese, founded in 2009, is a spiritual and social pillar of the province.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="diocese_subtitle_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="diocese_subtitle_sw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="diocese_subtitle_fr",
            field=models.TextField(
                blank=True,
                default="L'Église Anglicane du Diocèse de Makamba, fondée en 2009, est un pilier spirituel et social de la province du Burundi.",
            ),
        ),
    ]
