# Generated by Django 5.0.4 on 2026-03-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0021_sitesettings_diocese_subtitle_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="diocese_subtitle_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="diocese_subtitle_rn",
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="diocese_subtitle_fr",
            field=models.TextField(
                blank=True,
                default="L'Église Anglicane du Diocèse de Makamba, fondée en 2009, est un pilier spirituel et social de la province de Makamba au Burundi.",
            ),
        ),
    ]
