# Generated by Django 5.0.4 on 2026-03-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0022_remove_sitesettings_diocese_subtitle_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="vision_description_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="vision_description_fr",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="vision_description_rn",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="vision_title_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="vision_title_fr",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="vision_title_rn",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="diocese_name_fr",
            field=models.CharField(
                blank=True, default="Diocèse de Makamba", max_length=200
            ),
        ),
    ]
