# Generated by Django 5.0.4 on 2026-03-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0023_remove_sitesettings_vision_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="vision_description_en",
            field=models.TextField(
                blank=True,
                default="Rooted in the Gospel, the Diocese of Makamba is committed to serving God and the community through three fundamental pillars.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_description_fr",
            field=models.TextField(
                blank=True,
                default="Enraciné dans l'Évangile, le Diocèse de Makamba s'engage à servir Dieu et la communauté à travers trois piliers fondamentaux.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_description_rn",
            field=models.TextField(
                blank=True,
                default="Bishingiye ku Njili, Diyoseze ya Makamba yiyemeje gukorera Imana n'abanyagihugu biciye mu nkingi zitatu z'ibanze.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_title_en",
            field=models.CharField(
                blank=True, default="Our Vision & Mission", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_title_fr",
            field=models.CharField(
                blank=True, default="Notre Vision & Mission", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_title_rn",
            field=models.CharField(
                blank=True, default="Iciyago n'Ubutumwa bwacu", max_length=200
            ),
        ),
    ]
