# Generated by Django 5.0.4 on 2026-02-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MissionAxe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="Axe de mission"),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Axe de Mission",
                "verbose_name_plural": "Axes de Mission",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Membre de l'équipe",
                "verbose_name_plural": "Équipe Diocésaine",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(max_length=50, verbose_name="Année / Période"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Titre de l'événement"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description détaillée")),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Ordre d'affichage"),
                ),
            ],
            options={
                "verbose_name": "Événement Historique",
                "verbose_name_plural": "Chronologie - Historique",
                "ordering": ["order", "year"],
            },
        ),
        migrations.CreateModel(
            name="VisionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Nom Lucide (Cross, Heart, Users, etc.)",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Valeur",
                "verbose_name_plural": "Valeurs",
                "ordering": ["order"],
            },
        ),
    ]
