# Generated by Django 5.0.4 on 2026-02-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="team/", verbose_name="Photo de profil"
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="history/",
                verbose_name="Image de l'événement",
            ),
        ),
    ]
