# Generated by Django 5.0.4 on 2026-02-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_teammember_image_timelineevent_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiocesePresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texte de l'historique"
                    ),
                ),
                (
                    "history_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="diocese/",
                        verbose_name="Image de l'historique",
                    ),
                ),
                (
                    "bishop_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom de l'évêque",
                    ),
                ),
                (
                    "bishop_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Message de l'évêque"
                    ),
                ),
                (
                    "bishop_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="diocese/",
                        verbose_name="Photo de l'évêque",
                    ),
                ),
                (
                    "organization_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texte sur l'organisation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Présentation du Diocèse",
                "verbose_name_plural": "Présentation du Diocèse",
            },
        ),
    ]
