# Generated by Django 5.0.4 on 2026-03-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_diocesepresentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="diocesepresentation",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="diocese/",
                verbose_name="Image Hero (Bandeau)",
            ),
        ),
        migrations.AddField(
            model_name="missionaxe",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="axes/", verbose_name="Photo de l'axe"
            ),
        ),
        migrations.AddField(
            model_name="visionvalue",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="values/",
                verbose_name="Photo de la valeur",
            ),
        ),
    ]
