# Generated by Django 5.0.4 on 2026-03-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_diocesepresentation_hero_image_missionaxe_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diocesepresentation",
            name="bishop_message",
        ),
        migrations.RemoveField(
            model_name="diocesepresentation",
            name="history_text",
        ),
        migrations.RemoveField(
            model_name="diocesepresentation",
            name="organization_text",
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="bishop_message_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Message de l'évêque (EN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="bishop_message_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Message de l'évêque (FR)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="bishop_message_rn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Message de l'évêque (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="bishop_message_sw",
            field=models.TextField(
                blank=True, null=True, verbose_name="Message de l'évêque (SW)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="history_text_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Texte de l'historique (EN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="history_text_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Texte de l'historique (FR)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="history_text_rn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Texte de l'historique (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="history_text_sw",
            field=models.TextField(
                blank=True, null=True, verbose_name="Texte de l'historique (SW)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="organization_text_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Texte sur l'organisation (EN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="organization_text_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Texte sur l'organisation (FR)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="organization_text_rn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Texte sur l'organisation (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="organization_text_sw",
            field=models.TextField(
                blank=True, null=True, verbose_name="Texte sur l'organisation (SW)"
            ),
        ),
        migrations.AddField(
            model_name="missionaxe",
            name="language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("rn", "Kirundi"),
                    ("en", "English"),
                    ("sw", "Kiswahili"),
                ],
                default="fr",
                max_length=2,
                verbose_name="Langue",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("rn", "Kirundi"),
                    ("en", "English"),
                    ("sw", "Kiswahili"),
                ],
                default="fr",
                max_length=2,
                verbose_name="Langue",
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("rn", "Kirundi"),
                    ("en", "English"),
                    ("sw", "Kiswahili"),
                ],
                default="fr",
                max_length=2,
                verbose_name="Langue",
            ),
        ),
        migrations.AddField(
            model_name="visionvalue",
            name="language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("rn", "Kirundi"),
                    ("en", "English"),
                    ("sw", "Kiswahili"),
                ],
                default="fr",
                max_length=2,
                verbose_name="Langue",
            ),
        ),
    ]
