# Generated by Django 5.0.4 on 2026-03-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_diocesepresentation_hero_subtitle_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_description_en",
            field=models.TextField(
                blank=True,
                default="Rooted in the Gospel, the Diocese of Makamba is committed to serving God and communities through three fundamental pillars.",
                null=True,
                verbose_name="Description Vision (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_description_fr",
            field=models.TextField(
                blank=True,
                default="Fondé sur l'Évangile, le Diocèse de Makamba s'engage à servir Dieu et les communautés à travers trois piliers fondamentaux.",
                null=True,
                verbose_name="Description Vision (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_description_rn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Vision (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_description_sw",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Vision (SW)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_title_en",
            field=models.CharField(
                blank=True,
                default="Our Vision and Mission",
                max_length=255,
                null=True,
                verbose_name="Titre Vision (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_title_fr",
            field=models.CharField(
                blank=True,
                default="Notre vision et notre mission",
                max_length=255,
                null=True,
                verbose_name="Titre Vision (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_title_rn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre Vision (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_title_sw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre Vision (SW)"
            ),
        ),
    ]
