# Generated by Django 5.0.4 on 2026-03-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_diocesepresentation_vision_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diocesepresentation",
            name="history_title_en",
            field=models.CharField(
                blank=True,
                default="Major Timeline (Key Dates)",
                max_length=255,
                null=True,
                verbose_name="Titre Historique (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="history_title_fr",
            field=models.CharField(
                blank=True,
                default="Chronologie Majeure (Dates Clés)",
                max_length=255,
                null=True,
                verbose_name="Titre Historique (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="history_title_rn",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre Historique (RN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="history_title_sw",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre Historique (SW)",
            ),
        ),
    ]
