# Generated by Django 5.0.4 on 2026-03-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_diocesepresentation_history_title_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineevent",
            name="title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre de l'événement",
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="year",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Année / Période"
            ),
        ),
    ]
