# Generated by Django 5.0.4 on 2026-03-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_alter_timelineevent_title_alter_timelineevent_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="diocese/",
                verbose_name="Image de la vision/mission",
            ),
        ),
    ]
