# Generated by Django 5.0.4 on 2026-03-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_diocesepresentation_vision_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Mission (EN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_description_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Mission (FR)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_description_rn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Mission (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_description_sw",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Mission (SW)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="diocese/",
                verbose_name="Image de la Mission",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_title_en",
            field=models.CharField(
                blank=True,
                default="Our Mission",
                max_length=255,
                null=True,
                verbose_name="Titre Mission (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_title_fr",
            field=models.CharField(
                blank=True,
                default="Notre Mission",
                max_length=255,
                null=True,
                verbose_name="Titre Mission (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_title_rn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre Mission (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_title_sw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre Mission (SW)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Valeurs (EN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_description_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Valeurs (FR)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_description_rn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Valeurs (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_description_sw",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Valeurs (SW)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="diocese/",
                verbose_name="Image des Valeurs",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_title_en",
            field=models.CharField(
                blank=True,
                default="Our Values",
                max_length=255,
                null=True,
                verbose_name="Titre Valeurs (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_title_fr",
            field=models.CharField(
                blank=True,
                default="Nos Valeurs",
                max_length=255,
                null=True,
                verbose_name="Titre Valeurs (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_title_rn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre Valeurs (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_title_sw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre Valeurs (SW)"
            ),
        ),
        migrations.AlterField(
            model_name="diocesepresentation",
            name="vision_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Vision (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="diocesepresentation",
            name="vision_description_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Vision (FR)"
            ),
        ),
        migrations.AlterField(
            model_name="diocesepresentation",
            name="vision_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="diocese/",
                verbose_name="Image de la Vision",
            ),
        ),
        migrations.AlterField(
            model_name="diocesepresentation",
            name="vision_title_en",
            field=models.CharField(
                blank=True,
                default="Our Vision",
                max_length=255,
                null=True,
                verbose_name="Titre Vision (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="diocesepresentation",
            name="vision_title_fr",
            field=models.CharField(
                blank=True,
                default="Notre Vision",
                max_length=255,
                null=True,
                verbose_name="Titre Vision (FR)",
            ),
        ),
    ]
