# Generated by Django 5.0.4 on 2026-03-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_diocesepresentation_mission_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diocesepresentation",
            name="team_badge_en",
            field=models.CharField(
                blank=True,
                default="Leadership",
                max_length=255,
                null=True,
                verbose_name="Badge Équipe (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="team_badge_fr",
            field=models.CharField(
                blank=True,
                default="Leadership",
                max_length=255,
                null=True,
                verbose_name="Badge Équipe (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="team_badge_rn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Badge Équipe (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="team_badge_sw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Badge Équipe (SW)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="team_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Équipe (EN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="team_description_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Équipe (FR)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="team_description_rn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Équipe (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="team_description_sw",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description Équipe (SW)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="team_title_en",
            field=models.CharField(
                blank=True,
                default="The Diocesan Team",
                max_length=255,
                null=True,
                verbose_name="Titre Équipe (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="team_title_fr",
            field=models.CharField(
                blank=True,
                default="L'Équipe Diocésaine",
                max_length=255,
                null=True,
                verbose_name="Titre Équipe (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="team_title_rn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre Équipe (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="team_title_sw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre Équipe (SW)"
            ),
        ),
    ]
