# Generated by Django 5.0.4 on 2026-03-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_diocesepresentation_team_badge_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diocesepresentation",
            name="bishop_title_en",
            field=models.CharField(
                blank=True,
                default="Bishop of Makamba",
                max_length=255,
                null=True,
                verbose_name="Titre de l'évêque (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="bishop_title_fr",
            field=models.CharField(
                blank=True,
                default="Évêque de Makamba",
                max_length=255,
                null=True,
                verbose_name="Titre de l'évêque (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="bishop_title_rn",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre de l'évêque (RN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="bishop_title_sw",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre de l'évêque (SW)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_badge_en",
            field=models.CharField(
                blank=True,
                default="Strategy",
                max_length=255,
                null=True,
                verbose_name="Badge Mission (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_badge_fr",
            field=models.CharField(
                blank=True,
                default="Stratégie",
                max_length=255,
                null=True,
                verbose_name="Badge Mission (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_badge_rn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Badge Mission (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="mission_badge_sw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Badge Mission (SW)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="organization_subtitle_en",
            field=models.CharField(
                blank=True,
                default="Presentation of the Anglican Diocese of MAKAMBA.",
                max_length=255,
                null=True,
                verbose_name="Sous-titre Organisation (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="organization_subtitle_fr",
            field=models.CharField(
                blank=True,
                default="Présentation du Diocèse Anglican de MAKAMBA.",
                max_length=255,
                null=True,
                verbose_name="Sous-titre Organisation (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="organization_subtitle_rn",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sous-titre Organisation (RN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="organization_subtitle_sw",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sous-titre Organisation (SW)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="organization_title_en",
            field=models.CharField(
                blank=True,
                default="Our Origin & Organisation",
                max_length=255,
                null=True,
                verbose_name="Titre Organisation (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="organization_title_fr",
            field=models.CharField(
                blank=True,
                default="Notre Origine & Organisation",
                max_length=255,
                null=True,
                verbose_name="Titre Organisation (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="organization_title_rn",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre Organisation (RN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="organization_title_sw",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre Organisation (SW)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_badge_en",
            field=models.CharField(
                blank=True,
                default="Values",
                max_length=255,
                null=True,
                verbose_name="Badge Valeurs (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_badge_fr",
            field=models.CharField(
                blank=True,
                default="Étiquette",
                max_length=255,
                null=True,
                verbose_name="Badge Valeurs (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_badge_rn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Badge Valeurs (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="values_badge_sw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Badge Valeurs (SW)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_badge_en",
            field=models.CharField(
                blank=True,
                default="Idealism",
                max_length=255,
                null=True,
                verbose_name="Badge Vision (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_badge_fr",
            field=models.CharField(
                blank=True,
                default="Idéalisme",
                max_length=255,
                null=True,
                verbose_name="Badge Vision (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_badge_rn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Badge Vision (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="vision_badge_sw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Badge Vision (SW)"
            ),
        ),
    ]
