# Generated by Django 5.0.4 on 2026-03-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_diocesepresentation_bishop_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diocesepresentation",
            name="hero_title_en",
            field=models.CharField(
                blank=True,
                default="The Diocese",
                max_length=255,
                null=True,
                verbose_name="Titre Hero (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="hero_title_fr",
            field=models.CharField(
                blank=True,
                default="Le Diocèse",
                max_length=255,
                null=True,
                verbose_name="Titre Hero (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="hero_title_rn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre Hero (RN)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="hero_title_sw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre Hero (SW)"
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_bishop_en",
            field=models.CharField(
                blank=True,
                default="The Bishop",
                max_length=255,
                null=True,
                verbose_name="Label Nav Évêque (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_bishop_fr",
            field=models.CharField(
                blank=True,
                default="L'Évêque",
                max_length=255,
                null=True,
                verbose_name="Label Nav Évêque (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_bishop_rn",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Label Nav Évêque (RN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_bishop_sw",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Label Nav Évêque (SW)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_history_en",
            field=models.CharField(
                blank=True,
                default="History",
                max_length=255,
                null=True,
                verbose_name="Label Nav Historique (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_history_fr",
            field=models.CharField(
                blank=True,
                default="Historique",
                max_length=255,
                null=True,
                verbose_name="Label Nav Historique (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_history_rn",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Label Nav Historique (RN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_history_sw",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Label Nav Historique (SW)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_team_en",
            field=models.CharField(
                blank=True,
                default="The Team",
                max_length=255,
                null=True,
                verbose_name="Label Nav Équipe (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_team_fr",
            field=models.CharField(
                blank=True,
                default="L'Équipe",
                max_length=255,
                null=True,
                verbose_name="Label Nav Équipe (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_team_rn",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Label Nav Équipe (RN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_team_sw",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Label Nav Équipe (SW)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_vision_en",
            field=models.CharField(
                blank=True,
                default="Vision & Mission",
                max_length=255,
                null=True,
                verbose_name="Label Nav Vision (EN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_vision_fr",
            field=models.CharField(
                blank=True,
                default="Vision & Mission",
                max_length=255,
                null=True,
                verbose_name="Label Nav Vision (FR)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_vision_rn",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Label Nav Vision (RN)",
            ),
        ),
        migrations.AddField(
            model_name="diocesepresentation",
            name="nav_vision_sw",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Label Nav Vision (SW)",
            ),
        ),
    ]
