# Generated by Django 5.0.4 on 2026-03-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_diocesepresentation_hero_title_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diocesepresentation",
            name="hero_subtitle_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Sous-titre Hero (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="diocesepresentation",
            name="hero_subtitle_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Sous-titre Hero (FR)"
            ),
        ),
        migrations.AlterField(
            model_name="diocesepresentation",
            name="hero_subtitle_rn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Sous-titre Hero (RN)"
            ),
        ),
        migrations.AlterField(
            model_name="diocesepresentation",
            name="hero_subtitle_sw",
            field=models.TextField(
                blank=True, null=True, verbose_name="Sous-titre Hero (SW)"
            ),
        ),
    ]
