# Generated by Django 5.0.4 on 2026-03-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_remove_diocesepresentation_bishop_message_rn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diocesepresentation",
            name="hero_subtitle_en",
            field=models.TextField(
                blank=True,
                default="The Anglican Church of Makamba Diocese, founded in 2009, is a spiritual and social pillar of the province.",
                null=True,
                verbose_name="Sous-titre Héro (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="diocesepresentation",
            name="hero_subtitle_fr",
            field=models.TextField(
                blank=True,
                default="L'Église Anglicane du Diocèse de Makamba, fondée en 2009, est un pilier spirituel et social de la province du Burundi.",
                null=True,
                verbose_name="Sous-titre Héro (FR)",
            ),
        ),
    ]
