# Generated by Django 5.0.4 on 2026-02-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="announcements/",
                verbose_name="Image / Affiche",
            ),
        ),
    ]
