# Generated by Django 5.0.4 on 2026-02-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_announcement_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="category",
            field=models.CharField(
                choices=[
                    ("temoignages", "Témoignages"),
                    ("evenements", "Événements"),
                    ("nouvelles", "Nouvelles"),
                ],
                default="nouvelles",
                max_length=20,
            ),
        ),
    ]
