# Generated by Django 5.0.4 on 2026-03-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0004_announcement_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="announcements/",
                verbose_name="Image à la une",
            ),
        ),
        migrations.CreateModel(
            name="AnnouncementImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="announcements/gallery/")),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="announcements.announcement",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
