# Generated by Django 5.0.4 on 2026-03-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0005_alter_announcement_image_announcementimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="content_en",
            field=models.TextField(blank=True, default="", verbose_name="Contenu (EN)"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="content_fr",
            field=models.TextField(default="", verbose_name="Contenu (FR)"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_en",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Titre (EN)"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_fr",
            field=models.CharField(
                default="", max_length=255, verbose_name="Titre (FR)"
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fr", "Français"),
                    ("rn", "Kirundi"),
                    ("en", "English"),
                    ("sw", "Kiswahili"),
                ],
                default="fr",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
