# Generated by Django 5.0.4 on 2026-03-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[("admin", "Administrateur"), ("user", "Utilisateur")],
                default="admin",
                help_text="admin = tous les droits, user = actualités et ressources uniquement",
                max_length=10,
            ),
        ),
    ]
