# Generated by Django 5.0.4 on 2026-02-27 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre du ministère"),
                ),
                ("mission", models.TextField(verbose_name="Mission / Description")),
                (
                    "icon",
                    models.CharField(
                        default="Users",
                        help_text="Nom de l'icône Lucide (ex: Users, Heart, BookOpen, Sprout)",
                        max_length=50,
                    ),
                ),
                (
                    "testimony_quote",
                    models.TextField(blank=True, verbose_name="Citation du témoignage"),
                ),
                (
                    "testimony_author",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Auteur du témoignage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ministère",
                "verbose_name_plural": "Ministères",
            },
        ),
        migrations.CreateModel(
            name="MinistryActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Titre de l'activité"
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="ministries.ministry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité de ministère",
                "verbose_name_plural": "Activités de ministère",
            },
        ),
    ]
