# Generated by Django 5.0.4 on 2026-03-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministries", "0003_ministry_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinistryPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ministries/",
                        verbose_name="Image Hero",
                    ),
                ),
                (
                    "hero_badge_fr",
                    models.CharField(
                        default="NOS ACTIONS",
                        max_length=255,
                        verbose_name="Badge Hero (FR)",
                    ),
                ),
                (
                    "hero_badge_rn",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Badge Hero (RN)",
                    ),
                ),
                (
                    "hero_badge_en",
                    models.CharField(
                        blank=True,
                        default="OUR ACTIONS",
                        max_length=255,
                        null=True,
                        verbose_name="Badge Hero (EN)",
                    ),
                ),
                (
                    "hero_badge_sw",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Badge Hero (SW)",
                    ),
                ),
                (
                    "hero_title_fr",
                    models.CharField(
                        default="Ministères",
                        max_length=255,
                        verbose_name="Titre Hero (FR)",
                    ),
                ),
                (
                    "hero_title_rn",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Titre Hero (RN)",
                    ),
                ),
                (
                    "hero_title_en",
                    models.CharField(
                        blank=True,
                        default="Ministries",
                        max_length=255,
                        null=True,
                        verbose_name="Titre Hero (EN)",
                    ),
                ),
                (
                    "hero_title_sw",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Titre Hero (SW)",
                    ),
                ),
                (
                    "hero_description_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description Hero (FR)"
                    ),
                ),
                (
                    "hero_description_rn",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description Hero (RN)"
                    ),
                ),
                (
                    "hero_description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description Hero (EN)"
                    ),
                ),
                (
                    "hero_description_sw",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description Hero (SW)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Ministères (Introduction)",
                "verbose_name_plural": "Page Ministères (Introduction)",
            },
        ),
        migrations.RemoveField(
            model_name="ministry",
            name="language",
        ),
        migrations.RemoveField(
            model_name="ministry",
            name="mission",
        ),
        migrations.RemoveField(
            model_name="ministry",
            name="testimony_quote",
        ),
        migrations.RemoveField(
            model_name="ministry",
            name="title",
        ),
        migrations.RemoveField(
            model_name="ministryactivity",
            name="title",
        ),
        migrations.AddField(
            model_name="ministry",
            name="mission_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mission / Description (EN)"
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="mission_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mission / Description (FR)"
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="mission_rn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mission / Description (RN)"
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="mission_sw",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mission / Description (SW)"
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name="ministry",
            name="testimony_quote_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Citation du témoignage (EN)"
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="testimony_quote_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Citation du témoignage (FR)"
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="testimony_quote_rn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Citation du témoignage (RN)"
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="testimony_quote_sw",
            field=models.TextField(
                blank=True, null=True, verbose_name="Citation du témoignage (SW)"
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="title_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre du ministère (EN)",
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="title_fr",
            field=models.CharField(
                default="Ministère",
                max_length=255,
                verbose_name="Titre du ministère (FR)",
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="title_rn",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre du ministère (RN)",
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="title_sw",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre du ministère (SW)",
            ),
        ),
        migrations.AddField(
            model_name="ministryactivity",
            name="title_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre de l'activité (EN)",
            ),
        ),
        migrations.AddField(
            model_name="ministryactivity",
            name="title_fr",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre de l'activité (FR)",
            ),
        ),
        migrations.AddField(
            model_name="ministryactivity",
            name="title_rn",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre de l'activité (RN)",
            ),
        ),
        migrations.AddField(
            model_name="ministryactivity",
            name="title_sw",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre de l'activité (SW)",
            ),
        ),
        migrations.AlterField(
            model_name="ministry",
            name="testimony_author",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Auteur du témoignage",
            ),
        ),
    ]
