# Generated by Django 5.0.4 on 2026-03-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ministries", "0004_ministrypage_remove_ministry_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ministry",
            name="mission_rn",
        ),
        migrations.RemoveField(
            model_name="ministry",
            name="mission_sw",
        ),
        migrations.RemoveField(
            model_name="ministry",
            name="testimony_quote_rn",
        ),
        migrations.RemoveField(
            model_name="ministry",
            name="testimony_quote_sw",
        ),
        migrations.RemoveField(
            model_name="ministry",
            name="title_rn",
        ),
        migrations.RemoveField(
            model_name="ministry",
            name="title_sw",
        ),
        migrations.RemoveField(
            model_name="ministryactivity",
            name="title_rn",
        ),
        migrations.RemoveField(
            model_name="ministryactivity",
            name="title_sw",
        ),
        migrations.RemoveField(
            model_name="ministrypage",
            name="hero_badge_rn",
        ),
        migrations.RemoveField(
            model_name="ministrypage",
            name="hero_badge_sw",
        ),
        migrations.RemoveField(
            model_name="ministrypage",
            name="hero_description_rn",
        ),
        migrations.RemoveField(
            model_name="ministrypage",
            name="hero_description_sw",
        ),
        migrations.RemoveField(
            model_name="ministrypage",
            name="hero_title_rn",
        ),
        migrations.RemoveField(
            model_name="ministrypage",
            name="hero_title_sw",
        ),
    ]
