# Generated by Django 5.0.4 on 2026-01-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-sermon_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Ou télécharger un fichier audio', null=True, upload_to='sermons/audio/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sermons/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='sermon_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_file',
            field=models.FileField(blank=True, help_text='Ou télécharger un fichier vidéo', null=True, upload_to='sermons/videos/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
