# Generated by Django 5.0.4 on 2026-02-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0002_alter_sermon_options_alter_sermon_audio_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("video", "Vidéo"),
                    ("audio", "Audio"),
                    ("youtube", "YouTube"),
                ],
                default="video",
                max_length=10,
            ),
        ),
    ]
