# Generated by Django 5.0.4 on 2026-03-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0003_sermon_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("video", "Vidéo"),
                    ("audio", "Audio"),
                    ("youtube", "YouTube"),
                    ("document", "Document"),
                ],
                default="video",
                max_length=10,
            ),
        ),
    ]
