# Generated by Django 5.0.4 on 2026-03-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0004_alter_sermon_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="document_file",
            field=models.FileField(
                blank=True,
                help_text="Ou télécharger un document (PDF, Word, etc.)",
                null=True,
                upload_to="sermons/documents/",
            ),
        ),
    ]
