# Generated by Django 5.0.4 on 2026-03-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0005_sermon_document_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sermoncategory",
            options={
                "ordering": ["name_fr"],
                "verbose_name_plural": "Sermon categories",
            },
        ),
        migrations.AddField(
            model_name="sermon",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sermon",
            name="description_fr",
            field=models.TextField(default="", verbose_name="Description (FR)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sermon",
            name="language_primary",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English")],
                default="fr",
                max_length=2,
                verbose_name="Langue du média",
            ),
        ),
        migrations.AddField(
            model_name="sermon",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Titre (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sermon",
            name="title_fr",
            field=models.CharField(
                default="Sermon", max_length=200, verbose_name="Titre (FR)"
            ),
        ),
        migrations.AddField(
            model_name="sermoncategory",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (EN)"),
        ),
        migrations.AddField(
            model_name="sermoncategory",
            name="description_fr",
            field=models.TextField(blank=True, verbose_name="Description (FR)"),
        ),
        migrations.AddField(
            model_name="sermoncategory",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sermoncategory",
            name="name_fr",
            field=models.CharField(
                default="Catégorie", max_length=100, verbose_name="Nom (FR)"
            ),
        ),
        migrations.AlterField(
            model_name="sermon",
            name="description",
            field=models.TextField(
                blank=True, help_text="OBSOLÈTE: Utiliser description_fr/en", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sermon",
            name="language",
            field=models.CharField(
                blank=True,
                help_text="OBSOLÈTE: Utiliser language_primary",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sermon",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="OBSOLÈTE: Utiliser title_fr/en",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sermoncategory",
            name="description",
            field=models.TextField(
                blank=True, help_text="OBSOLÈTE: Utiliser description_fr/en", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sermoncategory",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="OBSOLÈTE: Utiliser name_fr/en",
                max_length=100,
                null=True,
            ),
        ),
    ]
